Repository nspcc-dev/neofs-dev-env, pull requests merged in 2020-12, with the labels that each got.

#19 Add S3 Gate
  .env
  .services
  services/s3_gate/.env
  services/s3_gate/.hosts
  services/s3_gate/.s3.env
  services/s3_gate/docker-compose.yml
  services/s3_gate/hcs.pub.key
  services/s3_gate/hcs.sec.key
  services/s3_gate/tls.crt
  services/s3_gate/tls.key
  services/s3_gate/user.key
Labels: enhancement

#18 Fix make up error on mac.
  Makefile
Labels: bug

#23 Update HTTP Gate
  .env
Labels: enhancement

#24 Update to new NeoFS S3 release
  .env
  services/s3_gate/.hosts
  services/s3_gate/docker-compose.yml
Labels: enhancement

#26 macOS workaround
  README.md
  docs/macos.md
Labels: documentation, enhancement

#28 Update gates images
  .env
Labels: enhancement
